repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: Run 'isort' import statement sorter on Python code
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    name: Run 'black' formatter on Python code
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.278
  hooks:
  - id: ruff
    name: Linting using 'ruff'
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
    name: Static type checking with mypy
