def get_xfails(parameterization):
    reasons = {
        "doc2vec,lstm-base": "incompatible methods",
        "doc2vec,lstm-pool": "incompatible methods",
        "doc2vec,nb": "incompatible methods",
        "doc2vec,nn-2-layer": "tbd",
        "doc2vec,rf": "tbd",
        "doc2vec,svm": "tbd",
        "embedding-idf,logistic": "issue #34",
        "embedding-idf,lstm-base": "issue #34 + incompatible methods",
        "embedding-idf,lstm-pool": "issue #34 + incompatible methods",
        "embedding-idf,nb": "issue #34",
        "embedding-idf,nn-2-layer": "issue #34",
        "embedding-idf,rf": "issue #34",
        "embedding-idf,svm": "issue #34",
        "embedding-lstm,logistic": "incompatible methods",
        "embedding-lstm,lstm-base": "issue #20",
        "embedding-lstm,lstm-pool": "issue #20",
        "embedding-lstm,nb": "incompatible methods",
        "embedding-lstm,nn-2-layer": "incompatible methods + issue #33",
        "embedding-lstm,rf": "incompatible methods",
        "embedding-lstm,svm": "incompatible methods",
        "sbert,lstm-base": "incompatible methods",
        "sbert,lstm-pool": "incompatible methods",
        "sbert,nb": "incompatible methods",
        "sbert,nn-2-layer": "issue #33",
        "tfidf,lstm-base": "incompatible methods",
        "tfidf,lstm-pool": "incompatible methods",
        "tfidf,nn-2-layer": "issue #33",
    }
    present = parameterization in reasons.keys()
    return present, reasons[parameterization] if present else ""
