from tests.helpers._get_xfails_mocked import get_xfails_mocked


msg = "'asreview simulate' doesn't use its '--embedding' argument (#34)"


def get_xfails(parameterization):
    reasons = {
        "doc2vec,lstm-base": get_xfails_mocked(parameterization)[1],
        "doc2vec,lstm-pool": get_xfails_mocked(parameterization)[1],
        "doc2vec,nb": "to verify: nb can't handle negative values generated by doc2vec",
        "embedding-idf,logistic": msg,
        "embedding-idf,lstm-base": f"{msg}, {get_xfails_mocked(parameterization)[1]}",
        "embedding-idf,lstm-pool": f"{msg}, {get_xfails_mocked(parameterization)[1]}",
        "embedding-idf,nb": msg,
        "embedding-idf,nn-2-layer": msg,
        "embedding-idf,rf": msg,
        "embedding-idf,svm": msg,
        "sbert,lstm-base": get_xfails_mocked(parameterization)[1],
        "sbert,lstm-pool": get_xfails_mocked(parameterization)[1],
        "sbert,nb": "to verify: nb can't handle negative values generated by sbert",
        "tfidf,lstm-base": get_xfails_mocked(parameterization)[1],
        "tfidf,lstm-pool": get_xfails_mocked(parameterization)[1],
    }
    present = parameterization in reasons.keys()
    return present, reasons[parameterization] if present else ""
