def get_xfails(parameterization):
    reasons = {
        "logistic,embedding-idf": "issue #34",
        "logistic,embedding-lstm": "incompatible methods",
        "lstm-base,doc2vec": "incompatible methods",
        "lstm-base,embedding-idf": "incompatible methods + issue #34",
        "lstm-base,embedding-lstm": "issue #20",
        "lstm-base,sbert": "incompatible methods",
        "lstm-base,tfidf": "incompatible methods",
        "lstm-pool,doc2vec": "incompatible methods",
        "lstm-pool,embedding-idf": "incompatible methods + issue #34",
        "lstm-pool,embedding-lstm": "issue #20",
        "lstm-pool,sbert": "incompatible methods",
        "lstm-pool,tfidf": "incompatible methods",
        "nb,doc2vec": "incompatible methods",
        "nb,embedding-idf": "issue #34",
        "nb,embedding-lstm": "incompatible methods",
        "nb,sbert": "incompatible methods",
        "nn-2-layer,doc2vec": "tbd",
        "nn-2-layer,embedding-idf": "issue #34",
        "nn-2-layer,embedding-lstm": "incompatible methods + issue #33",
        "nn-2-layer,sbert": "issue #33",
        "nn-2-layer,tfidf": "issue #33",
        "rf,doc2vec": "tbd",
        "rf,embedding-idf": "issue #34",
        "rf,embedding-lstm": "incompatible methods",
        "svm,doc2vec": "tbd",
        "svm,embedding-idf": "issue #34",
        "svm,embedding-lstm": "incompatible methods",
    }
    present = parameterization in reasons.keys()
    return present, reasons[parameterization] if present else ""
