from tests.helpers.get_xfails_mocked import get_xfails_mocked


def get_xfails(parameterization):
    reasons = {
        "doc2vec,lstm-base": get_xfails_mocked(parameterization)[1],
        "doc2vec,lstm-pool": get_xfails_mocked(parameterization)[1],
        "doc2vec,nb": "to verify: nb can't handle negative values generated by doc2vec",
        "embedding-idf,logistic": get_xfails_mocked(parameterization)[1],
        "embedding-idf,lstm-base": get_xfails_mocked(parameterization)[1],
        "embedding-idf,lstm-pool": get_xfails_mocked(parameterization)[1],
        "embedding-idf,nb": get_xfails_mocked(parameterization)[1],
        "embedding-idf,nn-2-layer": get_xfails_mocked(parameterization)[1],
        "embedding-idf,rf": get_xfails_mocked(parameterization)[1],
        "embedding-idf,svm": get_xfails_mocked(parameterization)[1],
        "sbert,lstm-base": get_xfails_mocked(parameterization)[1],
        "sbert,lstm-pool": get_xfails_mocked(parameterization)[1],
        "sbert,nb": "to verify: nb can't handle negative values generated by sbert",
        "tfidf,lstm-base": get_xfails_mocked(parameterization)[1],
        "tfidf,lstm-pool": get_xfails_mocked(parameterization)[1],
    }
    present = parameterization in reasons.keys()
    return present, reasons[parameterization] if present else ""
