name: dbg

on:
  workflow_dispatch:

jobs:

  first:
    name: download
    runs-on: ubuntu-latest
    steps:
      - name: Create ~/asr_data directory with embedding file in it
        shell: bash
        run: |
          mkdir ~/asr_data
          cd ~/asr_data
          curl https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz -o fasttext.cc.en.300.vec.gz
          gunzip fasttext.cc.en.300.vec.gz
      - name: Commit embedding data to cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/asr_data/fasttext.cc.en.300.vec
          key: thekey
          enableCrossOsArchive: true

  second:
    name: show
    needs: first
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest']    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Retrieve embedding data from cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/asr_data/fasttext.cc.en.300.vec
          key: thekey
      - shell: bash
        run: |
          stat ~/asr_data/fasttext.cc.en.300.vec
