name: dbg

on:
  workflow_dispatch:

jobs:

  first:
    name: download
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          curl https://raw.githubusercontent.com/asreview-tuning/asreview-simulation/main/.zenodo.extras.json -o thefile.json
  second:
    name: show
    runs-on: ubuntu-latest
    needs: first
    steps:
      - shell: bash
        run: |
          cat thefile.json
