name: dbg

on:
  workflow_dispatch:

jobs:

  first:
    name: download
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir ~/asr_data
          echo "contents" > ~/asr_data/thefile.txt
          curl https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz -o fasttext.cc.en.300.vec.gz
          gunzip fasttext.cc.en.300.vec.gz
      - uses: actions/cache@v3.3.2
        with:
          path: fasttext.cc.en.300.vec
          key: thekey

  second:
    name: show
    runs-on: ubuntu-latest
    needs: first
    steps:
      - uses: actions/cache@v3.3.2
        with:
          path: fasttext.cc.en.300.vec
          key: thekey
      - shell: bash
        run: |
          stat fasttext.cc.en.300.vec
