name: dbg

on:
  workflow_dispatch:

jobs:
        
  first:
    name: download
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          curl https://raw.githubusercontent.com/asreview-tuning/asreview-simulation/main/.zenodo.extras.json -o thefile.json
      - uses: actions/cache@v3.3.2
        with:
          path: thefile.json
          key: thekey

  second:
    name: show
    runs-on: ubuntu-latest
    needs: first
    steps:
      - uses: actions/cache@v3.3.2
        with:
          path: thefile.json
          key: thekey
      - shell: bash
        run: |
          cat thefile.json
