name: sonarcloud

on:
  workflow_dispatch:
  schedule:
    - cron: 42 4 * * 2     #  04:42 on Tuesdays

jobs:
  setup:
    name: download
    runs-on: 'ubuntu-latest'
    steps:

      - name: Create $HOME/asr_data directory with embedding file in it
        shell: bash
        run: |
          mkdir $HOME/asr_data
          cd $HOME/asr_data
          curl https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz -o cc.en.300.vec.gz
          7z e cc.en.300.vec.gz
          mv cc.en.300.vec fasttext.cc.en.300.vec

      - name: Commit embedding data to cache
        uses: actions/cache/save@v3.3.2
        with:
          path: ~/asr_data/fasttext.cc.en.300.vec
          key: cachekey-${{ matrix.os }}-${{ github.run_id }}


  coverage:
    env:
      ASREVIEW_VERSION: '1.2.1'
      PYTHON_VERSION: '3.10'
      OS: 'ubuntu-latest'
    name: asr$ASREVIEW_VERSION-with-tf-py$PYTHON_VERSION-$OS
    runs-on: $OS
    needs: setup
    steps:

      - name: Retrieve embedding data from cache
        uses: actions/cache/restore@v3.3.2
        with:
          path: ~/asr_data/fasttext.cc.en.300.vec
          key: cachekey-$OS-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Get a copy of the code
        uses: actions/checkout@v3

      - name: Set up Python $PYTHON_VERSION
        uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION

      - name: Show Python info
        shell: bash
        run: |
          which python
          python --version

      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install asreview==$ASREVIEW_VERSION
          python3 -m pip install .[doc2vec,sbert,tensorflow,testing]

      - name: Run unit tests
        shell: bash
        run: pytest --cov=src/ tests/unit


  sonarcloud:
    name: publish
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
