name: testing

on:
 workflow_dispatch:

jobs:

  test:
    name: ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash
        run: |
          which python
          python --version
      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install .[testing]
      - name: Test
        shell: bash
        run: pytest -v
