name: testing

on:
  workflow_dispatch:
  schedule:
    - cron: 42 4 * * 2     #  04:42 on Tuesdays


jobs:

  test:
    name: asr${{ matrix.asreview-version }}-${{ matrix.tensorflow }}-py${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        asreview-version: [ '1.0.4', '1.1.1', '1.2.1' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [ '3.8', '3.9', '3.10', '3.11']
        tensorflow: ["with-tf", "wo-tf"]
        exclude:
          # On python >= 3.11, pip complains that tensorflow wants to be >= 2.10,
          # but asreview <= 1.2.1 wants tensorflow to be < 2.10
          - python-version: '3.8'
            tensorflow: 'without-tf'
          - python-version: '3.9'
            tensorflow: 'without-tf'
          - python-version: '3.10'
            tensorflow: 'without-tf'
          - python-version: '3.11'
            tensorflow: 'with-tf'
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python info
        shell: bash
        run: |
          which python
          python --version

      - if: ${{ matrix.tensorflow }} == 'with-tf'
        name: Install dependencies (with tensorflow)
        shell: bash
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install asreview==${{ matrix.asreview-version }}
          python3 -m pip install .[doc2vec,sbert,tensorflow,testing]

      - if: ${{ matrix.tensorflow }} == 'without-tf'
        name: Install dependencies (without tensorflow)
        shell: bash
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install asreview==${{ matrix.asreview-version }}
          python3 -m pip install .[doc2vec,sbert,testing]

      # - name: Run unit tests
      #   shell: bash
      #   # embedding based fex needs a 2G file that it currently doesn't have on GitHub
      #   run: pytest -m 'not fex_embedding_idf and not fex_embedding_lstm' tests/unit

      # - name: Run mocked tests
      #   shell: bash
      #   # embedding based fex needs a 2G file that it currently doesn't have on GitHub
      #   run: pytest -m 'not fex_embedding_idf and not fex_embedding_lstm' tests/mocked

      # - if: matrix.tensorflow == 'with-tf'
      #   name: Run integration tests
      #   shell: bash
      #   # fex_embedding and fex_lstm need a 2G file that it currently doesn't have on GitHub
      #   # fex_sbert takes too long and causes timeout errors
      #   run: pytest -m 'not fex_embedding_idf and not fex_embedding_lstm and not fex_sbert' tests/it

      # - if: matrix.tensorflow == 'without-tf'
      #   name: Run integration tests
      #   shell: bash
      #   # fex_embedding and fex_lstm need a 2G file that it currently doesn't have on GitHub
      #   # fex_sbert takes too long and causes timeout errors
      #   # cls_nn_2_layer needs tensorflow that has install problems for py > 3.10
      #   run: pytest -m 'not fex_embedding_idf and not fex_embedding_lstm and not fex_sbert and not cls_nn_2_layer' tests/it
