name: zenodraft
on:
  # Trigger manually
  workflow_dispatch

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v4

        - name: Create a draft snapshot of the repository contents as a new
                version in collection 8042547 on Zenodo
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          uses: zenodraft/action@0.13.3
          with:
            collection: 8042547
            upsert-doi: true
            upsert-location: identifiers[3]
            publish: false
            sandbox: false
