name: zenodraft
on:
  workflow_dispatch: null     # This workflow is triggered manually

permissions:
  contents: write

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v4

        - name: Convert CITATION.cff to .zenodo.citation.json
          uses: citation-file-format/cffconvert-github-action@2.0.0
          with:
            args: "--infile ./CITATION.cff --format zenodo --outfile .zenodo.citation.json"

        - name: Combine .zenodo.citation.json with .zenodo.extras.json
          run: |
            cat .zenodo.citation.json .zenodo.extras.json | jq -s add > ${{ runner.temp }}/.zenodo.json
            rm .zenodo.citation.json

        - name: Create a draft snapshot of the repository contents as a new
                version in collection 8042547 on Zenodo
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          uses: zenodraft/action@0.13.3
          with:
            concept: 8042547
            metadata: ${{ runner.temp }}/.zenodo.json
            publish: false
            sandbox: false
            upsert-doi: true
            upsert-location: identifiers[3]
